"""creacion de tabla

Revision ID: 0536cae6d433
Revises: d9f454f39428
Create Date: 2025-05-06 15:29:56.633287

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect  # ← Añade esto


# revision identifiers, used by Alembic.
revision = '0536cae6d433'
down_revision = 'd9f454f39428'
branch_labels = None
depends_on = None

def upgrade():
    # Verifica si la tabla ya existe (opcional)
    inspector = inspect(op.get_bind())
    if not inspector.has_table('genero_productos'):
        op.create_table(
            'genero_productos',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('nombre', sa.String(length=50), nullable=False),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('nombre')
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_genero')

    op.drop_table('genero_productos')
    # ### end Alembic commands ###
