""" PONEMOS RELACIONES DE PRODUCTOS Y TALLAS AL HISTORIAL STOCK2

Revision ID: 058ae75d1239
Revises: eafbb1e27c32
Create Date: 2025-05-19 15:34:19.957469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '058ae75d1239'
down_revision = 'eafbb1e27c32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historial_stock', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'productos', ['id_producto'], ['id'])
        batch_op.create_foreign_key(None, 'tallas', ['id_talla'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historial_stock', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
