"""volvemos a la version anterior de productos

Revision ID: 5b9b6db0b4cb
Revises: 936c7bfc7576
Create Date: 2025-05-15 15:04:55.576503

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5b9b6db0b4cb'
down_revision = '936c7bfc7576'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_column('genero')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genero', mysql.VARCHAR(length=10), nullable=False))

    # ### end Alembic commands ###
