""" VEREMOS SI FUNCIONA

Revision ID: 845fafc28d0a
Revises: d7a23f181ee5
Create Date: 2025-05-14 12:09:32.290402

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '845fafc28d0a'
down_revision = 'd7a23f181ee5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventario', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'tallas', ['id_talla'], ['id'])
        batch_op.drop_column('talla')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('talla', mysql.VARCHAR(length=10), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
