"""Creamos una tabla llamda genero para la redirección al crear una prenda

Revision ID: 936c7bfc7576
Revises: ad729ab5fe2a
Create Date: 2025-05-15 12:03:31.780422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '936c7bfc7576'
down_revision = 'ad729ab5fe2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genero', sa.String(length=10), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_column('genero')

    # ### end Alembic commands ###
