"""Agregramos la talla a carrito producto

Revision ID: 9ea671afe8ff
Revises: d45960d08982
Create Date: 2025-05-07 15:36:09.149086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ea671afe8ff'
down_revision = 'd45960d08982'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carrito_productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('talla', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carrito_productos', schema=None) as batch_op:
        batch_op.drop_column('talla')

    # ### end Alembic commands ###
