"""RELACION GENERO CON PRODUCTOS

Revision ID: cd4adb727597
Revises: b6d03289f52a
Create Date: 2025-05-15 15:27:51.106069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd4adb727597'
down_revision = 'b6d03289f52a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_genero', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'genero', ['id_genero'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_genero')

    # ### end Alembic commands ###
