"""BORRAMOS LAS TABLAS detalle_factura, factura y pedidos

Revision ID: ce3bee299325
Revises: cd4adb727597
Create Date: 2025-05-19 11:41:31.684371

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ce3bee299325'
down_revision = 'cd4adb727597'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('facturas')
    op.drop_table('pedidos')
   
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facturas',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('id_pedido', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('monto_total', mysql.FLOAT(), nullable=False),
    sa.Column('fecha_emision', mysql.DATETIME(), nullable=True),
    sa.Column('estado', mysql.VARCHAR(length=20), nullable=True),
    sa.ForeignKeyConstraint(['id_pedido'], ['pedidos.id'], name='facturas_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('pedidos',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('fecha_pedido', sa.DATE(), nullable=True),
    sa.Column('estado_pedido', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('total_pedido', mysql.FLOAT(), nullable=False),
    sa.Column('direccion_envio', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('id_usuario', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('id_metodo_pago', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_metodo_pago'], ['metodos_pago.id'], name='pedidos_ibfk_1'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], name='pedidos_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('detalle_facturas',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('id_factura', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('id_producto', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('cantidad', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_factura'], ['facturas.id'], name='detalle_facturas_ibfk_1'),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id'], name='detalle_facturas_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
