"""hola hombres ymujeres

Revision ID: d3ae42c27d35
Revises: d5eb29ae918a
Create Date: 2025-05-06 15:04:13.172564

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd3ae42c27d35'
down_revision = 'd5eb29ae918a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('parent_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'categorias', ['parent_id'], ['id'])

    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.alter_column('estado',
               existing_type=mysql.VARCHAR(length=30),
               type_=sa.String(length=10),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.alter_column('estado',
               existing_type=sa.String(length=10),
               type_=mysql.VARCHAR(length=30),
               existing_nullable=True)

    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('parent_id')
        batch_op.drop_column('tipo')

    # ### end Alembic commands ###
