"""eliminar tabla genero_productos y su relación

Revision ID: d45960d08982
Revises: 0536cae6d433
Create Date: 2025-05-06 17:13:44.915018

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd45960d08982'
down_revision = '0536cae6d433'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('genero_productos', schema=None) as batch_op:
        batch_op.drop_index('nombre')

    op.drop_table('genero_productos')
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_column('id_genero')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_genero', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))

    op.create_table('genero_productos',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('genero_productos', schema=None) as batch_op:
        batch_op.create_index('nombre', ['nombre'], unique=True)

    # ### end Alembic commands ###
