"""soluconado lo de cloudinary

Revision ID: d5eb29ae918a
Revises: 0e864dc9a918
Create Date: 2025-05-03 13:11:08.660335

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd5eb29ae918a'
down_revision = '0e864dc9a918'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagen_url', sa.String(length=500), nullable=True))
        batch_op.drop_column('imagen_public_id')
        batch_op.drop_column('imagen')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagen', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('imagen_public_id', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('imagen_url')

    # ### end Alembic commands ###
