"""Solo quite una cosa en talla

Revision ID: d7a23f181ee5
Revises: c8f51746a5cb
Create Date: 2025-05-14 11:32:13.581285

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd7a23f181ee5'
down_revision = 'c8f51746a5cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tallas', schema=None) as batch_op:
        batch_op.drop_column('categoria_talla')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tallas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categoria_talla', mysql.VARCHAR(length=50), nullable=True))

    # ### end Alembic commands ###
