"""holax

Revision ID: d9f454f39428
Revises: d3ae42c27d35
Create Date: 2025-05-06 15:16:03.285006

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd9f454f39428'
down_revision = 'd3ae42c27d35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.drop_constraint('categorias_ibfk_1', type_='foreignkey')
        batch_op.drop_column('tipo')
        batch_op.drop_column('parent_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('tipo', mysql.VARCHAR(length=20), nullable=False))
        batch_op.create_foreign_key('categorias_ibfk_1', 'categorias', ['parent_id'], ['id'])

    # ### end Alembic commands ###
