"""Agregamos un HistorialStock

Revision ID: eafbb1e27c32
Revises: ce3bee299325
Create Date: 2025-05-19 12:23:55.538640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eafbb1e27c32'
down_revision = 'ce3bee299325'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historial_stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_inventario', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('stock_anterior', sa.Integer(), nullable=False),
    sa.Column('stock_nuevo', sa.Integer(), nullable=False),
    sa.Column('diferencia', sa.Integer(), nullable=False),
    sa.Column('fecha_cambio', sa.DateTime(), nullable=False),
    sa.Column('motivo', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['id_inventario'], ['inventario.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('historial_stock')
    # ### end Alembic commands ###
